using System;
using System.Collections.Generic;
using System.Text;
using System.Data;

namespace Unnamed.LookupBox
{
    class SampleDataSet
    {
        public static DataSet createSampleDataSet()
        {
            List<String> dataList = getSampleDataList();

            DataSet ds = new System.Data.DataSet();
            foreach (string dataString in dataList)
            {
                String[] tokens = dataString.Split(new char[] { '\t' });
                if (ds.Tables.Contains(tokens[0]) == false)
                {
                    DataTable dt_new = ds.Tables.Add(tokens[0]);
                    dt_new.Columns.Add("id", typeof(string));
                    dt_new.Columns.Add("name", typeof(string));
                    dt_new.Columns.Add("category", typeof(string));
                    dt_new.Columns.Add("desc", typeof(string));
                }
                DataTable dt = ds.Tables[tokens[0]];
                DataRow dr = dt.Rows.Add();
                dr["id"] = tokens[1];
                dr["name"] = tokens[2];
                dr["category"] = tokens[3];
                dr["desc"] = "Sample Desc Here";
            }

            return ds;
        }

        private static List<String> getSampleDataList()
        {
            List<String> dataList = new List<string>();
            dataList.Add("Stocks\t13010\tKYOKUYO CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t13320\tNippon Suisan Kaisha,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t13330\tMaruha Nichiro Corporation\tAsia/Tokyo");
            dataList.Add("Stocks\t13520\tHOHSUI CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t13770\tSAKATA SEED CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t13790\tHOKUTO CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t14140\tSHO-BOND Holdings Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t14170\tMIRAIT Holdings Corporation\tAsia/Tokyo");
            dataList.Add("Stocks\t14190\tTama Home Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t14200\tSanyo Homes Corporation\tAsia/Tokyo");
            dataList.Add("Stocks\t15140\tSumiseki Holdings,Inc.\tAsia/Tokyo");
            dataList.Add("Stocks\t15150\tNittetsu Mining Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t15180\tMITSUI MATSUSHIMA CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t16050\tINPEX CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t16060\tJapan Drilling Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t16620\tJapan Petroleum Exploration Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t16630\tK&O Energy Group Inc.\tAsia/Tokyo");
            dataList.Add("Stocks\t17120\tDaiseki Eco.Solution Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t17190\tHAZAMA ANDO CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t17200\tTOKYU CONSTRUCTION CO., LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t17210\tCOMSYS Holdings Corporation\tAsia/Tokyo");
            dataList.Add("Stocks\t17220\tMISAWA HOMES CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t17620\tTAKAMATSU CONSTRUCTION GROUP CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t17660\tTOKEN CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t17800\tYAMAURA CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18010\tTAISEI CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18020\tOBAYASHI CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18030\tSHIMIZU CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18050\tTOBISHIMA CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18080\tHASEKO Corporation\tAsia/Tokyo");
            dataList.Add("Stocks\t18100\tMATSUI CONSTRUCTION CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18110\tTHE ZENITAKA CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18120\tKAJIMA CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18130\tFudo Tetra Corporation\tAsia/Tokyo");
            dataList.Add("Stocks\t18140\tDAISUE CONSTRUCTION CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18150\tTEKKEN CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18190\tNIPPON STEEL & SUMIKIN TEXENG.CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18200\tNishimatsu Construction Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t18210\tSumitomo Mitsui Construction Co., Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t18220\tDAIHO CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18240\tMAEDA CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18260\tSata Construction Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t18270\tNAKANO CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18330\tOKUMURA CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18340\tDaiwa Odakyu Construction Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t18350\tTOTETSU KOGYO CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18470\tICHIKEN Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t18520\tASANUMA CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18600\tTODA CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18610\tKumagai Gumi Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t18650\tAsunaro Aoki Construction Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t18660\tKITANO CONSTRUCTION CORP.,\tAsia/Tokyo");
            dataList.Add("Stocks\t18670\tUEKI CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18680\tMitsui Home Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t18700\tYAHAGI CONSTRUCTION CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18710\tP.S. Mitsubishi Construction Co., Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t18730\tHIGASHI NIHON HOUSE CO.,LTD\tAsia/Tokyo");
            dataList.Add("Stocks\t18780\tDAITO TRUST CONSTRUCTION CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18790\tSHINNIHON CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18810\tNIPPO CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18820\tTOA ROAD CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18830\tMAEDA ROAD CONSTRUCTION CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18840\tTHE NIPPON ROAD CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18850\tTOA CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18880\tWAKACHIKU CONSTRUCTION CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18900\tTOYO CONSTRUCTION CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18930\tPENTA-OCEAN CONSTRUCTION CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18960\tOBAYASHI ROAD CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t18980\tSEIKITOKYU KOGYO CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t18990\tFUKUDA CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t19090\tNippon Dry-Chemical CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19110\tSumitomo Forestry Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t19140\tJAPAN FOUNDATION ENGINEERING CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19160\tNISSEI BUILD KOGYO CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19190\tYAMADA SXL HOME CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19210\tTOMOE CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t19240\tPanaHome Corporation\tAsia/Tokyo");
            dataList.Add("Stocks\t19250\tDAIWA HOUSE INDUSTRY CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19260\tRAITO KOGYO CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19280\tSekisui House,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t19290\tNITTOC CONSTRUCTION CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19300\tHOKURIKU ELECTRICAL CONSTRUCTION CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19340\tYURTEC CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t19370\tSeibu Electric Industry Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t19390\tYONDENKO CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t19410\tCHUDENKO CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t19420\tKANDENKO CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19440\tKINDEN CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t19450\tTOKYO ENERGY & SYSTEMS INC.\tAsia/Tokyo");
            dataList.Add("Stocks\t19460\tTOENEC CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t19490\tSUMITOMO DENSETSU CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19500\tNIPPON DENSETSU KOGYO CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19510\tKYOWA EXEO CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t19520\tShin Nippon Air Technologies Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t19540\tNippon Koei Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t19560\tNDS CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19590\tKYUDENKO CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t19610\tSANKI ENGINEERING CO.,LTD.\tAsia/Tokyo");
            dataList.Add("Stocks\t19630\tJGC CORPORATION\tAsia/Tokyo");
            dataList.Add("Stocks\t19640\tChugai Ro Co.,Ltd.\tAsia/Tokyo");
            dataList.Add("Stocks\t000020\t동화약품\tAsia/KRX");
            dataList.Add("Stocks\t000030\t우리은행\tAsia/KRX");
            dataList.Add("Stocks\t000040\tKR모터스\tAsia/KRX");
            dataList.Add("Stocks\t000050\t경방\tAsia/KRX");
            dataList.Add("Stocks\t000060\t메리츠화재\tAsia/KRX");
            dataList.Add("Stocks\t000070\t삼양홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t000075\t삼양홀딩스우\tAsia/KRX");
            dataList.Add("Stocks\t000080\t하이트진로\tAsia/KRX");
            dataList.Add("Stocks\t000087\t하이트진로2우B\tAsia/KRX");
            dataList.Add("Stocks\t000100\t유한양행\tAsia/KRX");
            dataList.Add("Stocks\t000105\t유한양행우\tAsia/KRX");
            dataList.Add("Stocks\t000120\tCJ대한통운\tAsia/KRX");
            dataList.Add("Stocks\t000140\t하이트진로홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t000145\t하이트진로홀딩스우\tAsia/KRX");
            dataList.Add("Stocks\t000150\t두산\tAsia/KRX");
            dataList.Add("Stocks\t000155\t두산우\tAsia/KRX");
            dataList.Add("Stocks\t000157\t두산2우B\tAsia/KRX");
            dataList.Add("Stocks\t000180\t성창기업지주\tAsia/KRX");
            dataList.Add("Stocks\t000210\t대림산업\tAsia/KRX");
            dataList.Add("Stocks\t000215\t대림산업우\tAsia/KRX");
            dataList.Add("Stocks\t000220\t유유제약\tAsia/KRX");
            dataList.Add("Stocks\t000225\t유유제약1우\tAsia/KRX");
            dataList.Add("Stocks\t000227\t유유제약2우B\tAsia/KRX");
            dataList.Add("Stocks\t000230\t일동제약\tAsia/KRX");
            dataList.Add("Stocks\t000240\t한국타이어월드와이드\tAsia/KRX");
            dataList.Add("Stocks\t000270\t기아차\tAsia/KRX");
            dataList.Add("Stocks\t000300\t대유신소재\tAsia/KRX");
            dataList.Add("Stocks\t000320\t노루홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t000325\t노루홀딩스우\tAsia/KRX");
            dataList.Add("Stocks\t000327\t노루홀딩스2우B\tAsia/KRX");
            dataList.Add("Stocks\t000360\t삼환기업\tAsia/KRX");
            dataList.Add("Stocks\t000365\t삼환기업우\tAsia/KRX");
            dataList.Add("Stocks\t000370\t한화손해보험\tAsia/KRX");
            dataList.Add("Stocks\t000390\t삼화페인트\tAsia/KRX");
            dataList.Add("Stocks\t000400\t롯데손해보험\tAsia/KRX");
            dataList.Add("Stocks\t000420\t로케트전기\tAsia/KRX");
            dataList.Add("Stocks\t000425\t로케트전우\tAsia/KRX");
            dataList.Add("Stocks\t000430\t대원강업\tAsia/KRX");
            dataList.Add("Stocks\t000480\t조선내화\tAsia/KRX");
            dataList.Add("Stocks\t000490\t대동공업\tAsia/KRX");
            dataList.Add("Stocks\t000500\t가온전선\tAsia/KRX");
            dataList.Add("Stocks\t000520\t삼일제약\tAsia/KRX");
            dataList.Add("Stocks\t000540\t흥국화재\tAsia/KRX");
            dataList.Add("Stocks\t000545\t흥국화재우\tAsia/KRX");
            dataList.Add("Stocks\t000547\t흥국화재2우B\tAsia/KRX");
            dataList.Add("Stocks\t000590\tCS홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t000640\t동아쏘시오홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t000650\t천일고속\tAsia/KRX");
            dataList.Add("Stocks\t000660\tSK하이닉스\tAsia/KRX");
            dataList.Add("Stocks\t000670\t영풍\tAsia/KRX");
            dataList.Add("Stocks\t000680\tLS네트웍스\tAsia/KRX");
            dataList.Add("Stocks\t000687\tLS네트웍스전환상환2?\tAsia/KRX");
            dataList.Add("Stocks\t000700\t유수홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t000720\t현대건설\tAsia/KRX");
            dataList.Add("Stocks\t000725\t현대건설우\tAsia/KRX");
            dataList.Add("Stocks\t000760\t이화산업\tAsia/KRX");
            dataList.Add("Stocks\t000800\t경남기업\tAsia/KRX");
            dataList.Add("Stocks\t000810\t삼성화재\tAsia/KRX");
            dataList.Add("Stocks\t000815\t삼성화재우\tAsia/KRX");
            dataList.Add("Stocks\t000830\t삼성물산\tAsia/KRX");
            dataList.Add("Stocks\t000835\t삼성물산우\tAsia/KRX");
            dataList.Add("Stocks\t000850\t화천기공\tAsia/KRX");
            dataList.Add("Stocks\t000860\t건설화학\tAsia/KRX");
            dataList.Add("Stocks\t000880\t한화\tAsia/KRX");
            dataList.Add("Stocks\t000885\t한화우\tAsia/KRX");
            dataList.Add("Stocks\t000890\t보해양조\tAsia/KRX");
            dataList.Add("Stocks\t000895\t보해양조우\tAsia/KRX");
            dataList.Add("Stocks\t000910\t유니온\tAsia/KRX");
            dataList.Add("Stocks\t000950\t전방\tAsia/KRX");
            dataList.Add("Stocks\t000970\t한국주철관\tAsia/KRX");
            dataList.Add("Stocks\t000990\t동부하이텍\tAsia/KRX");
            dataList.Add("Stocks\t000995\t동부하이텍1우\tAsia/KRX");
            dataList.Add("Stocks\t000997\t동부하이텍2우B\tAsia/KRX");
            dataList.Add("Stocks\t001020\t페이퍼코리아\tAsia/KRX");
            dataList.Add("Stocks\t001040\tCJ\tAsia/KRX");
            dataList.Add("Stocks\t001045\tCJ우\tAsia/KRX");
            dataList.Add("Stocks\t001060\tJW중외제약\tAsia/KRX");
            dataList.Add("Stocks\t001065\tJW중외제약우\tAsia/KRX");
            dataList.Add("Stocks\t001067\tJW중외제약2우B\tAsia/KRX");
            dataList.Add("Stocks\t001070\t대한방직\tAsia/KRX");
            dataList.Add("Stocks\t001080\t만호제강\tAsia/KRX");
            dataList.Add("Stocks\t001120\tLG상사\tAsia/KRX");
            dataList.Add("Stocks\t001130\t대한제분\tAsia/KRX");
            dataList.Add("Stocks\t001140\t국보\tAsia/KRX");
            dataList.Add("Stocks\t001200\t유진투자증권\tAsia/KRX");
            dataList.Add("Stocks\t001210\t금호전기\tAsia/KRX");
            dataList.Add("Stocks\t001230\t동국제강\tAsia/KRX");
            dataList.Add("Stocks\t001250\tGS글로벌\tAsia/KRX");
            dataList.Add("Stocks\t001260\t남광토건\tAsia/KRX");
            dataList.Add("Stocks\t001270\t부국증권\tAsia/KRX");
            dataList.Add("Stocks\t001275\t부국증권우\tAsia/KRX");
            dataList.Add("Stocks\t001290\t골든브릿지증권\tAsia/KRX");
            dataList.Add("Stocks\t001340\t백광산업\tAsia/KRX");
            dataList.Add("Stocks\t001360\t삼성제약\tAsia/KRX");
            dataList.Add("Stocks\t001380\tSG충남방적\tAsia/KRX");
            dataList.Add("Stocks\t001390\tKG케미칼\tAsia/KRX");
            dataList.Add("Stocks\t001420\t태원물산\tAsia/KRX");
            dataList.Add("Stocks\t001430\t세아베스틸\tAsia/KRX");
            dataList.Add("Stocks\t001440\t대한전선\tAsia/KRX");
            dataList.Add("Stocks\t001450\t현대해상\tAsia/KRX");
            dataList.Add("Stocks\t001460\tBYC\tAsia/KRX");
            dataList.Add("Stocks\t001465\tBYC우\tAsia/KRX");
            dataList.Add("Stocks\t001470\t삼부토건\tAsia/KRX");
            dataList.Add("Stocks\t001500\tHMC투자증권\tAsia/KRX");
            dataList.Add("Stocks\t001510\tSK증권\tAsia/KRX");
            dataList.Add("Stocks\t001515\tSK증권우\tAsia/KRX");
            dataList.Add("Stocks\t001520\t동양\tAsia/KRX");
            dataList.Add("Stocks\t001525\t동양우\tAsia/KRX");
            dataList.Add("Stocks\t001527\t동양2우B\tAsia/KRX");
            dataList.Add("Stocks\t001529\t동양3우B\tAsia/KRX");
            dataList.Add("Stocks\t001530\t동일방직\tAsia/KRX");
            dataList.Add("Stocks\t001550\t조비\tAsia/KRX");
            dataList.Add("Stocks\t001560\t제일연마\tAsia/KRX");
            dataList.Add("Stocks\t001570\t금양\tAsia/KRX");
            dataList.Add("Stocks\t001620\t동국실업\tAsia/KRX");
            dataList.Add("Stocks\t001630\t종근당홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t001680\t대상\tAsia/KRX");
            dataList.Add("Stocks\t001685\t대상우\tAsia/KRX");
            dataList.Add("Stocks\t001689\t대상3우B\tAsia/KRX");
            dataList.Add("Stocks\t001720\t신영증권\tAsia/KRX");
            dataList.Add("Stocks\t001725\t신영증권우\tAsia/KRX");
            dataList.Add("Stocks\t001740\tSK네트웍스\tAsia/KRX");
            dataList.Add("Stocks\t001745\tSK네트웍스우\tAsia/KRX");
            dataList.Add("Stocks\t001750\t한양증권\tAsia/KRX");
            dataList.Add("Stocks\t001755\t한양증권우\tAsia/KRX");
            dataList.Add("Stocks\t001770\t신화실업\tAsia/KRX");
            dataList.Add("Stocks\t001780\t동양강철\tAsia/KRX");
            dataList.Add("Stocks\t001790\t대한제당\tAsia/KRX");
            dataList.Add("Stocks\t001795\t대한제당우\tAsia/KRX");
            dataList.Add("Stocks\t001799\t대한제당3우B\tAsia/KRX");
            dataList.Add("Stocks\t001800\t오리온\tAsia/KRX");
            dataList.Add("Stocks\t001820\t삼화콘덴서\tAsia/KRX");
            dataList.Add("Stocks\t001880\t삼호\tAsia/KRX");
            dataList.Add("Stocks\t001940\tKISCO홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t002000\t한국유리\tAsia/KRX");
            dataList.Add("Stocks\t002005\t한국유리우\tAsia/KRX");
            dataList.Add("Stocks\t002020\t코오롱\tAsia/KRX");
            dataList.Add("Stocks\t002025\t코오롱우\tAsia/KRX");
            dataList.Add("Stocks\t002030\t아세아\tAsia/KRX");
            dataList.Add("Stocks\t002070\t남영비비안\tAsia/KRX");
            dataList.Add("Stocks\t002100\t경농\tAsia/KRX");
            dataList.Add("Stocks\t002140\t고려산업\tAsia/KRX");
            dataList.Add("Stocks\t002150\t도화엔지니어링\tAsia/KRX");
            dataList.Add("Stocks\t002170\t삼양통상\tAsia/KRX");
            dataList.Add("Stocks\t002200\t수출포장\tAsia/KRX");
            dataList.Add("Stocks\t002210\t동성제약\tAsia/KRX");
            dataList.Add("Stocks\t002220\t한일철강\tAsia/KRX");
            dataList.Add("Stocks\t002240\t고려제강\tAsia/KRX");
            dataList.Add("Stocks\t002250\t근화제약\tAsia/KRX");
            dataList.Add("Stocks\t002270\t롯데푸드\tAsia/KRX");
            dataList.Add("Stocks\t002300\t한국제지\tAsia/KRX");
            dataList.Add("Stocks\t002310\t아세아제지\tAsia/KRX");
            dataList.Add("Stocks\t002320\t한진\tAsia/KRX");
            dataList.Add("Stocks\t002350\t넥센타이어\tAsia/KRX");
            dataList.Add("Stocks\t002355\t넥센타이어1우B\tAsia/KRX");
            dataList.Add("Stocks\t002360\tSH에너지화학\tAsia/KRX");
            dataList.Add("Stocks\t002380\tKCC\tAsia/KRX");
            dataList.Add("Stocks\t002390\t한독\tAsia/KRX");
            dataList.Add("Stocks\t002410\t범양건영\tAsia/KRX");
            dataList.Add("Stocks\t002420\t세기상사\tAsia/KRX");
            dataList.Add("Stocks\t002450\t삼익악기\tAsia/KRX");
            dataList.Add("Stocks\t002460\t화성산업\tAsia/KRX");
            dataList.Add("Stocks\t002550\tLIG손해보험\tAsia/KRX");
            dataList.Add("Stocks\t002600\t조흥\tAsia/KRX");
            dataList.Add("Stocks\t002620\t제일약품\tAsia/KRX");
            dataList.Add("Stocks\t002630\t오리엔트바이오\tAsia/KRX");
            dataList.Add("Stocks\t002700\t신일산업\tAsia/KRX");
            dataList.Add("Stocks\t002710\tTCC동양\tAsia/KRX");
            dataList.Add("Stocks\t002720\t국제약품\tAsia/KRX");
            dataList.Add("Stocks\t002760\t보락\tAsia/KRX");
            dataList.Add("Stocks\t002780\t진흥기업\tAsia/KRX");
            dataList.Add("Stocks\t002785\t진흥기업우B\tAsia/KRX");
            dataList.Add("Stocks\t002787\t진흥기업2우B\tAsia/KRX");
            dataList.Add("Stocks\t002790\t아모레G\tAsia/KRX");
            dataList.Add("Stocks\t002795\t아모레G우\tAsia/KRX");
            dataList.Add("Stocks\t002810\t삼영무역\tAsia/KRX");
            dataList.Add("Stocks\t002820\t선창산업\tAsia/KRX");
            dataList.Add("Stocks\t002840\t미원상사\tAsia/KRX");
            dataList.Add("Stocks\t002870\t신풍제지\tAsia/KRX");
            dataList.Add("Stocks\t002880\t대유에이텍\tAsia/KRX");
            dataList.Add("Stocks\t002900\t동양물산\tAsia/KRX");
            dataList.Add("Stocks\t002920\t유성기업\tAsia/KRX");
            dataList.Add("Stocks\t002960\t한국쉘석유\tAsia/KRX");
            dataList.Add("Stocks\t002990\t금호산업\tAsia/KRX");
            dataList.Add("Stocks\t002995\t금호산업우\tAsia/KRX");
            dataList.Add("Stocks\t003000\t부광약품\tAsia/KRX");
            dataList.Add("Stocks\t003010\t혜인\tAsia/KRX");
            dataList.Add("Stocks\t003030\t세아제강\tAsia/KRX");
            dataList.Add("Stocks\t003060\t슈넬생명과학\tAsia/KRX");
            dataList.Add("Stocks\t003070\t코오롱글로벌\tAsia/KRX");
            dataList.Add("Stocks\t003075\t코오롱글로벌우\tAsia/KRX");
            dataList.Add("Stocks\t003080\t성보화학\tAsia/KRX");
            dataList.Add("Stocks\t003090\t대웅\tAsia/KRX");
            dataList.Add("Stocks\t003120\t일성신약\tAsia/KRX");
            dataList.Add("Stocks\t003160\t디아이\tAsia/KRX");
            dataList.Add("Stocks\t003200\t일신방직\tAsia/KRX");
            dataList.Add("Stocks\t003220\t대원제약\tAsia/KRX");
            dataList.Add("Stocks\t003230\t삼양식품\tAsia/KRX");
            dataList.Add("Stocks\t003240\t태광산업\tAsia/KRX");
            dataList.Add("Stocks\t003280\t흥아해운\tAsia/KRX");
            dataList.Add("Stocks\t003300\t한일시멘트\tAsia/KRX");
            dataList.Add("Stocks\t003350\t한국화장품제조\tAsia/KRX");
            dataList.Add("Stocks\t003410\t쌍용양회\tAsia/KRX");
            dataList.Add("Stocks\t003415\t쌍용양회우\tAsia/KRX");
            dataList.Add("Stocks\t003419\t쌍용양회3우B\tAsia/KRX");
            dataList.Add("Stocks\t003450\t현대증권\tAsia/KRX");
            dataList.Add("Stocks\t003460\t유화증권\tAsia/KRX");
            dataList.Add("Stocks\t003465\t유화증권우\tAsia/KRX");
            dataList.Add("Stocks\t003470\t유안타증권\tAsia/KRX");
            dataList.Add("Stocks\t003475\t유안타증권우\tAsia/KRX");
            dataList.Add("Stocks\t003480\t한진중공업홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t003490\t대한항공\tAsia/KRX");
            dataList.Add("Stocks\t003495\t대한항공우\tAsia/KRX");
            dataList.Add("Stocks\t003520\t영진약품\tAsia/KRX");
            dataList.Add("Stocks\t003530\t한화투자증권\tAsia/KRX");
            dataList.Add("Stocks\t003535\t한화투자증권우\tAsia/KRX");
            dataList.Add("Stocks\t003540\t대신증권\tAsia/KRX");
            dataList.Add("Stocks\t003545\t대신증권우\tAsia/KRX");
            dataList.Add("Stocks\t003547\t대신증권2우B\tAsia/KRX");
            dataList.Add("Stocks\t003550\tLG\tAsia/KRX");
            dataList.Add("Stocks\t003555\tLG우\tAsia/KRX");
            dataList.Add("Stocks\t003560\tIHQ\tAsia/KRX");
            dataList.Add("Stocks\t003570\tS&T중공업\tAsia/KRX");
            dataList.Add("Stocks\t003580\t동원\tAsia/KRX");
            dataList.Add("Stocks\t003600\tSK\tAsia/KRX");
            dataList.Add("Stocks\t003605\tSK우\tAsia/KRX");
            dataList.Add("Stocks\t003610\t방림\tAsia/KRX");
            dataList.Add("Stocks\t003620\t쌍용차\tAsia/KRX");
            dataList.Add("Stocks\t003650\t미창석유\tAsia/KRX");
            dataList.Add("Stocks\t003680\t한성기업\tAsia/KRX");
            dataList.Add("Stocks\t003690\t코리안리\tAsia/KRX");
            dataList.Add("Stocks\t003720\t삼영화학\tAsia/KRX");
            dataList.Add("Stocks\t003780\t진양산업\tAsia/KRX");
            dataList.Add("Stocks\t003830\t대한화섬\tAsia/KRX");
            dataList.Add("Stocks\t003850\t보령제약\tAsia/KRX");
            dataList.Add("Stocks\t003920\t남양유업\tAsia/KRX");
            dataList.Add("Stocks\t003925\t남양유업우\tAsia/KRX");
            dataList.Add("Stocks\t003940\t삼양제넥스\tAsia/KRX");
            dataList.Add("Stocks\t003945\t삼양제넥우\tAsia/KRX");
            dataList.Add("Stocks\t003960\t사조대림\tAsia/KRX");
            dataList.Add("Stocks\t004000\t삼성정밀화학\tAsia/KRX");
            dataList.Add("Stocks\t004020\t현대제철\tAsia/KRX");
            dataList.Add("Stocks\t004060\tSG세계물산\tAsia/KRX");
            dataList.Add("Stocks\t004080\t신흥\tAsia/KRX");
            dataList.Add("Stocks\t004090\t한국석유\tAsia/KRX");
            dataList.Add("Stocks\t004100\t태양금속\tAsia/KRX");
            dataList.Add("Stocks\t004105\t태양금속우\tAsia/KRX");
            dataList.Add("Stocks\t004130\t대덕GDS\tAsia/KRX");
            dataList.Add("Stocks\t004135\t대덕GDS우\tAsia/KRX");
            dataList.Add("Stocks\t004140\t동방\tAsia/KRX");
            dataList.Add("Stocks\t004150\t한솔홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t004170\t신세계\tAsia/KRX");
            dataList.Add("Stocks\t004200\t고려개발\tAsia/KRX");
            dataList.Add("Stocks\t004250\tNPC\tAsia/KRX");
            dataList.Add("Stocks\t004255\tNPC우\tAsia/KRX");
            dataList.Add("Stocks\t004270\t남성\tAsia/KRX");
            dataList.Add("Stocks\t004310\t현대약품\tAsia/KRX");
            dataList.Add("Stocks\t004360\t세방\tAsia/KRX");
            dataList.Add("Stocks\t004365\t세방우\tAsia/KRX");
            dataList.Add("Stocks\t004367\t세방2우B\tAsia/KRX");
            dataList.Add("Stocks\t004370\t농심\tAsia/KRX");
            dataList.Add("Stocks\t004380\t삼익THK\tAsia/KRX");
            dataList.Add("Stocks\t004410\t서울식품\tAsia/KRX");
            dataList.Add("Stocks\t004415\t서울식품우\tAsia/KRX");
            dataList.Add("Stocks\t004430\t송원산업\tAsia/KRX");
            dataList.Add("Stocks\t004450\t삼화왕관\tAsia/KRX");
            dataList.Add("Stocks\t004490\t세방전지\tAsia/KRX");
            dataList.Add("Stocks\t004540\t깨끗한나라\tAsia/KRX");
            dataList.Add("Stocks\t004545\t깨끗한나라우\tAsia/KRX");
            dataList.Add("Stocks\t004560\t현대비앤지스틸\tAsia/KRX");
            dataList.Add("Stocks\t004565\t현대비앤지스틸우\tAsia/KRX");
            dataList.Add("Stocks\t004690\t삼천리\tAsia/KRX");
            dataList.Add("Stocks\t004700\t조광피혁\tAsia/KRX");
            dataList.Add("Stocks\t004710\t한솔테크닉스\tAsia/KRX");
            dataList.Add("Stocks\t004720\t우리들제약\tAsia/KRX");
            dataList.Add("Stocks\t004740\t보루네오\tAsia/KRX");
            dataList.Add("Stocks\t004770\t써니전자\tAsia/KRX");
            dataList.Add("Stocks\t004800\t효성\tAsia/KRX");
            dataList.Add("Stocks\t004830\t덕성\tAsia/KRX");
            dataList.Add("Stocks\t004835\t덕성우\tAsia/KRX");
            dataList.Add("Stocks\t004840\tDRB동일\tAsia/KRX");
            dataList.Add("Stocks\t004870\t티웨이홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t004890\t동일산업\tAsia/KRX");
            dataList.Add("Stocks\t004910\t조광페인트\tAsia/KRX");
            dataList.Add("Stocks\t004920\t삼영홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t004960\t한신공영\tAsia/KRX");
            dataList.Add("Stocks\t004970\t신라교역\tAsia/KRX");
            dataList.Add("Stocks\t004980\t성신양회\tAsia/KRX");
            dataList.Add("Stocks\t004985\t성신양회우\tAsia/KRX");
            dataList.Add("Stocks\t004987\t성신양회2우B\tAsia/KRX");
            dataList.Add("Stocks\t004989\t성신양회3우B\tAsia/KRX");
            dataList.Add("Stocks\t004990\t롯데제과\tAsia/KRX");
            dataList.Add("Stocks\t005010\t휴스틸\tAsia/KRX");
            dataList.Add("Stocks\t005030\t부산주공\tAsia/KRX");
            dataList.Add("Stocks\t005070\t코스모신소재\tAsia/KRX");
            dataList.Add("Stocks\t005090\t삼광글라스\tAsia/KRX");
            dataList.Add("Stocks\t005110\t한창\tAsia/KRX");
            dataList.Add("Stocks\t005180\t빙그레\tAsia/KRX");
            dataList.Add("Stocks\t005190\t동성화학\tAsia/KRX");
            dataList.Add("Stocks\t005250\t녹십자홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t005255\t녹십자홀딩스1우\tAsia/KRX");
            dataList.Add("Stocks\t005257\t녹십자홀딩스2우\tAsia/KRX");
            dataList.Add("Stocks\t005300\t롯데칠성\tAsia/KRX");
            dataList.Add("Stocks\t005305\t롯데칠성우\tAsia/KRX");
            dataList.Add("Stocks\t005320\t국동\tAsia/KRX");
            dataList.Add("Stocks\t005360\t모나미\tAsia/KRX");
            dataList.Add("Stocks\t005380\t현대차\tAsia/KRX");
            dataList.Add("Stocks\t005385\t현대차우\tAsia/KRX");
            dataList.Add("Stocks\t005387\t현대차2우B\tAsia/KRX");
            dataList.Add("Stocks\t005389\t현대차3우B\tAsia/KRX");
            dataList.Add("Stocks\t005390\t신성통상\tAsia/KRX");
            dataList.Add("Stocks\t005420\t코스모화학\tAsia/KRX");
            dataList.Add("Stocks\t005430\t한국공항\tAsia/KRX");
            dataList.Add("Stocks\t005440\t현대그린푸드\tAsia/KRX");
            dataList.Add("Stocks\t005450\t신한\tAsia/KRX");
            dataList.Add("Stocks\t005490\tPOSCO\tAsia/KRX");
            dataList.Add("Stocks\t005500\t삼진제약\tAsia/KRX");
            dataList.Add("Stocks\t005610\t삼립식품\tAsia/KRX");
            dataList.Add("Stocks\t005620\t대성합동지주\tAsia/KRX");
            dataList.Add("Stocks\t005680\t삼영전자\tAsia/KRX");
            dataList.Add("Stocks\t005690\t파미셀\tAsia/KRX");
            dataList.Add("Stocks\t005720\t넥센\tAsia/KRX");
            dataList.Add("Stocks\t005725\t넥센우\tAsia/KRX");
            dataList.Add("Stocks\t005740\t크라운제과\tAsia/KRX");
            dataList.Add("Stocks\t005745\t크라운제우\tAsia/KRX");
            dataList.Add("Stocks\t005750\t대림B&Co\tAsia/KRX");
            dataList.Add("Stocks\t005800\t신영와코루\tAsia/KRX");
            dataList.Add("Stocks\t005810\t풍산홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t005820\t원림\tAsia/KRX");
            dataList.Add("Stocks\t005830\t동부화재\tAsia/KRX");
            dataList.Add("Stocks\t005850\t에스엘\tAsia/KRX");
            dataList.Add("Stocks\t005870\t휴니드\tAsia/KRX");
            dataList.Add("Stocks\t005880\t대한해운\tAsia/KRX");
            dataList.Add("Stocks\t005930\t삼성전자\tAsia/KRX");
            dataList.Add("Stocks\t005935\t삼성전자우\tAsia/KRX");
            dataList.Add("Stocks\t005940\tNH투자증권\tAsia/KRX");
            dataList.Add("Stocks\t005945\tNH투자증권우\tAsia/KRX");
            dataList.Add("Stocks\t005950\t이수화학\tAsia/KRX");
            dataList.Add("Stocks\t005960\t동부건설\tAsia/KRX");
            dataList.Add("Stocks\t005965\t동부건설우\tAsia/KRX");
            dataList.Add("Stocks\t005980\t성지건설\tAsia/KRX");
            dataList.Add("Stocks\t006040\t동원산업\tAsia/KRX");
            dataList.Add("Stocks\t006060\t화승인더\tAsia/KRX");
            dataList.Add("Stocks\t006090\t사조오양\tAsia/KRX");
            dataList.Add("Stocks\t006110\t삼아알미늄\tAsia/KRX");
            dataList.Add("Stocks\t006120\tSK케미칼\tAsia/KRX");
            dataList.Add("Stocks\t006125\tSK케미칼우\tAsia/KRX");
            dataList.Add("Stocks\t006200\t한국전자홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t006220\t제주은행\tAsia/KRX");
            dataList.Add("Stocks\t006260\tLS\tAsia/KRX");
            dataList.Add("Stocks\t006280\t녹십자\tAsia/KRX");
            dataList.Add("Stocks\t006340\t대원전선\tAsia/KRX");
            dataList.Add("Stocks\t006345\t대원전선우\tAsia/KRX");
            dataList.Add("Stocks\t006360\tGS건설\tAsia/KRX");
            dataList.Add("Stocks\t006370\t대구백화점\tAsia/KRX");
            dataList.Add("Stocks\t006380\t카프로\tAsia/KRX");
            dataList.Add("Stocks\t006390\t현대시멘트\tAsia/KRX");
            dataList.Add("Stocks\t006400\t삼성SDI\tAsia/KRX");
            dataList.Add("Stocks\t006405\t삼성SDI우\tAsia/KRX");
            dataList.Add("Stocks\t006490\t로엔케이\tAsia/KRX");
            dataList.Add("Stocks\t006570\t대림통상\tAsia/KRX");
            dataList.Add("Stocks\t006650\t대한유화\tAsia/KRX");
            dataList.Add("Stocks\t006660\t삼성공조\tAsia/KRX");
            dataList.Add("Stocks\t006740\t영풍제지\tAsia/KRX");
            dataList.Add("Stocks\t006800\t대우증권\tAsia/KRX");
            dataList.Add("Stocks\t006805\t대우증권우\tAsia/KRX");
            dataList.Add("Stocks\t006840\tAK홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t006880\t신송홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t006890\t태경화학\tAsia/KRX");
            dataList.Add("Stocks\t006980\t우성사료\tAsia/KRX");
            dataList.Add("Stocks\t007070\tGS리테일\tAsia/KRX");
            dataList.Add("Stocks\t007110\t일신석재\tAsia/KRX");
            dataList.Add("Stocks\t007120\t디올메디바이오\tAsia/KRX");
            dataList.Add("Stocks\t007160\t사조산업\tAsia/KRX");
            dataList.Add("Stocks\t007190\t한솔아트원제지\tAsia/KRX");
            dataList.Add("Stocks\t007197\t한솔아트원제지2우B\tAsia/KRX");
            dataList.Add("Stocks\t007210\t벽산\tAsia/KRX");
            dataList.Add("Stocks\t007280\t한국특수형강\tAsia/KRX");
            dataList.Add("Stocks\t007310\t오뚜기\tAsia/KRX");
            dataList.Add("Stocks\t007340\t동아타이어\tAsia/KRX");
            dataList.Add("Stocks\t007460\t나라케이아이씨\tAsia/KRX");
            dataList.Add("Stocks\t007540\t샘표식품\tAsia/KRX");
            dataList.Add("Stocks\t007570\t일양약품\tAsia/KRX");
            dataList.Add("Stocks\t007575\t일양약품우\tAsia/KRX");
            dataList.Add("Stocks\t007590\t동방아그로\tAsia/KRX");
            dataList.Add("Stocks\t007610\t선도전기\tAsia/KRX");
            dataList.Add("Stocks\t007630\t지에스인스트루\tAsia/KRX");
            dataList.Add("Stocks\t007660\t이수페타시스\tAsia/KRX");
            dataList.Add("Stocks\t007690\t국도화학\tAsia/KRX");
            dataList.Add("Stocks\t007700\tF&F\tAsia/KRX");
            dataList.Add("Stocks\t007810\t코리아써키트\tAsia/KRX");
            dataList.Add("Stocks\t007815\t코리아써우\tAsia/KRX");
            dataList.Add("Stocks\t007860\t서연\tAsia/KRX");
            dataList.Add("Stocks\t007980\t태평양물산\tAsia/KRX");
            dataList.Add("Stocks\t008000\t도레이케미칼\tAsia/KRX");
            dataList.Add("Stocks\t008020\t경남에너지\tAsia/KRX");
            dataList.Add("Stocks\t008040\t동아원\tAsia/KRX");
            dataList.Add("Stocks\t008060\t대덕전자\tAsia/KRX");
            dataList.Add("Stocks\t008110\t대동전자\tAsia/KRX");
            dataList.Add("Stocks\t008250\t이건산업\tAsia/KRX");
            dataList.Add("Stocks\t008260\tNI스틸\tAsia/KRX");
            dataList.Add("Stocks\t008350\t남선알미늄\tAsia/KRX");
            dataList.Add("Stocks\t008355\t남선알미우\tAsia/KRX");
            dataList.Add("Stocks\t008420\t문배철강\tAsia/KRX");
            dataList.Add("Stocks\t008490\t서흥\tAsia/KRX");
            dataList.Add("Stocks\t008500\t일정실업\tAsia/KRX");
            dataList.Add("Stocks\t008560\t메리츠종금증권\tAsia/KRX");
            dataList.Add("Stocks\t008600\t윌비스\tAsia/KRX");
            dataList.Add("Stocks\t008700\t아남전자\tAsia/KRX");
            dataList.Add("Stocks\t008705\t아남전자우\tAsia/KRX");
            dataList.Add("Stocks\t008730\t율촌화학\tAsia/KRX");
            dataList.Add("Stocks\t008770\t호텔신라\tAsia/KRX");
            dataList.Add("Stocks\t008775\t호텔신라우\tAsia/KRX");
            dataList.Add("Stocks\t008870\t금비\tAsia/KRX");
            dataList.Add("Stocks\t008900\t티이씨앤코\tAsia/KRX");
            dataList.Add("Stocks\t008930\t한미사이언스\tAsia/KRX");
            dataList.Add("Stocks\t008970\t동양철관\tAsia/KRX");
            dataList.Add("Stocks\t009070\tKCTC\tAsia/KRX");
            dataList.Add("Stocks\t009140\t경인전자\tAsia/KRX");
            dataList.Add("Stocks\t009150\t삼성전기\tAsia/KRX");
            dataList.Add("Stocks\t009155\t삼성전기우\tAsia/KRX");
            dataList.Add("Stocks\t009160\tSIMPAC\tAsia/KRX");
            dataList.Add("Stocks\t009180\t한솔로지스틱스\tAsia/KRX");
            dataList.Add("Stocks\t009190\t대양금속\tAsia/KRX");
            dataList.Add("Stocks\t009200\t무림페이퍼\tAsia/KRX");
            dataList.Add("Stocks\t009240\t한샘\tAsia/KRX");
            dataList.Add("Stocks\t009270\t신원\tAsia/KRX");
            dataList.Add("Stocks\t009275\t신원우\tAsia/KRX");
            dataList.Add("Stocks\t009290\t광동제약\tAsia/KRX");
            dataList.Add("Stocks\t009310\t참엔지니어링\tAsia/KRX");
            dataList.Add("Stocks\t009320\t대우부품\tAsia/KRX");
            dataList.Add("Stocks\t009410\t태영건설\tAsia/KRX");
            dataList.Add("Stocks\t009415\t태영건설우\tAsia/KRX");
            dataList.Add("Stocks\t009420\t한올바이오파마\tAsia/KRX");
            dataList.Add("Stocks\t009440\tKC그린홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t009450\t경동나비엔\tAsia/KRX");
            dataList.Add("Stocks\t009460\t한창제지\tAsia/KRX");
            dataList.Add("Stocks\t009470\t삼화전기\tAsia/KRX");
            dataList.Add("Stocks\t009540\t현대중공업\tAsia/KRX");
            dataList.Add("Stocks\t009580\t무림P&P\tAsia/KRX");
            dataList.Add("Stocks\t009680\t모토닉\tAsia/KRX");
            dataList.Add("Stocks\t009770\t삼정펄프\tAsia/KRX");
            dataList.Add("Stocks\t009810\t고려포리머\tAsia/KRX");
            dataList.Add("Stocks\t009830\t한화케미칼\tAsia/KRX");
            dataList.Add("Stocks\t009835\t한화케미칼우\tAsia/KRX");
            dataList.Add("Stocks\t009970\t영원무역홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t010040\t한국내화\tAsia/KRX");
            dataList.Add("Stocks\t010050\t우리종금\tAsia/KRX");
            dataList.Add("Stocks\t010060\tOCI\tAsia/KRX");
            dataList.Add("Stocks\t010100\t한국프랜지\tAsia/KRX");
            dataList.Add("Stocks\t010120\tLS산전\tAsia/KRX");
            dataList.Add("Stocks\t010130\t고려아연\tAsia/KRX");
            dataList.Add("Stocks\t010140\t삼성중공업\tAsia/KRX");
            dataList.Add("Stocks\t010145\t삼성중공우\tAsia/KRX");
            dataList.Add("Stocks\t010420\t한솔PNS\tAsia/KRX");
            dataList.Add("Stocks\t010520\t현대하이스코\tAsia/KRX");
            dataList.Add("Stocks\t010580\t지코\tAsia/KRX");
            dataList.Add("Stocks\t010600\t와이비로드\tAsia/KRX");
            dataList.Add("Stocks\t010620\t현대미포조선\tAsia/KRX");
            dataList.Add("Stocks\t010640\t진양폴리\tAsia/KRX");
            dataList.Add("Stocks\t010660\t화천기계\tAsia/KRX");
            dataList.Add("Stocks\t010690\t화신\tAsia/KRX");
            dataList.Add("Stocks\t010770\t평화홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t010780\t아이에스동서\tAsia/KRX");
            dataList.Add("Stocks\t010820\t퍼스텍\tAsia/KRX");
            dataList.Add("Stocks\t010950\tS-Oil\tAsia/KRX");
            dataList.Add("Stocks\t010955\tS-Oil우\tAsia/KRX");
            dataList.Add("Stocks\t010960\t삼호개발\tAsia/KRX");
            dataList.Add("Stocks\t011000\t진원생명과학\tAsia/KRX");
            dataList.Add("Stocks\t011070\tLG이노텍\tAsia/KRX");
            dataList.Add("Stocks\t011090\t에넥스\tAsia/KRX");
            dataList.Add("Stocks\t011150\tCJ씨푸드\tAsia/KRX");
            dataList.Add("Stocks\t011155\tCJ씨푸드1우\tAsia/KRX");
            dataList.Add("Stocks\t011160\t두산건설\tAsia/KRX");
            dataList.Add("Stocks\t011170\t롯데케미칼\tAsia/KRX");
            dataList.Add("Stocks\t011200\t현대상선\tAsia/KRX");
            dataList.Add("Stocks\t011210\t현대위아\tAsia/KRX");
            dataList.Add("Stocks\t011230\t삼화전자\tAsia/KRX");
            dataList.Add("Stocks\t011280\t태림포장\tAsia/KRX");
            dataList.Add("Stocks\t011300\t성안\tAsia/KRX");
            dataList.Add("Stocks\t011330\t유니켐\tAsia/KRX");
            dataList.Add("Stocks\t011390\t부산산업\tAsia/KRX");
            dataList.Add("Stocks\t011420\tIB월드와이드\tAsia/KRX");
            dataList.Add("Stocks\t011500\t한농화성\tAsia/KRX");
            dataList.Add("Stocks\t011690\t유양디앤유\tAsia/KRX");
            dataList.Add("Stocks\t011700\t한신기계\tAsia/KRX");
            dataList.Add("Stocks\t011720\t현대페인트\tAsia/KRX");
            dataList.Add("Stocks\t011760\t현대상사\tAsia/KRX");
            dataList.Add("Stocks\t011780\t금호석유\tAsia/KRX");
            dataList.Add("Stocks\t011785\t금호석유우\tAsia/KRX");
            dataList.Add("Stocks\t011790\tSKC\tAsia/KRX");
            dataList.Add("Stocks\t011810\tSTX\tAsia/KRX");
            dataList.Add("Stocks\t011930\t신성솔라에너지\tAsia/KRX");
            dataList.Add("Stocks\t012030\t동부CNI\tAsia/KRX");
            dataList.Add("Stocks\t012160\t영흥철강\tAsia/KRX");
            dataList.Add("Stocks\t012170\t키스톤글로벌\tAsia/KRX");
            dataList.Add("Stocks\t012200\t계양전기\tAsia/KRX");
            dataList.Add("Stocks\t012205\t계양전기우\tAsia/KRX");
            dataList.Add("Stocks\t012280\t영화금속\tAsia/KRX");
            dataList.Add("Stocks\t012320\t경동가스\tAsia/KRX");
            dataList.Add("Stocks\t012330\t현대모비스\tAsia/KRX");
            dataList.Add("Stocks\t012450\t삼성테크윈\tAsia/KRX");
            dataList.Add("Stocks\t012510\t더존비즈온\tAsia/KRX");
            dataList.Add("Stocks\t012600\t청호컴넷\tAsia/KRX");
            dataList.Add("Stocks\t012610\t경인양행\tAsia/KRX");
            dataList.Add("Stocks\t012630\t현대산업\tAsia/KRX");
            dataList.Add("Stocks\t012690\t모나리자\tAsia/KRX");
            dataList.Add("Stocks\t012750\t에스원\tAsia/KRX");
            dataList.Add("Stocks\t012800\t대창\tAsia/KRX");
            dataList.Add("Stocks\t013000\t세우글로벌\tAsia/KRX");
            dataList.Add("Stocks\t013360\t일성건설\tAsia/KRX");
            dataList.Add("Stocks\t013367\t일성건설2우B\tAsia/KRX");
            dataList.Add("Stocks\t013520\t화승알앤에이\tAsia/KRX");
            dataList.Add("Stocks\t013570\t디와이\tAsia/KRX");
            dataList.Add("Stocks\t013580\t계룡건설\tAsia/KRX");
            dataList.Add("Stocks\t013700\t삼환까뮤\tAsia/KRX");
            dataList.Add("Stocks\t013870\t지엠비코리아\tAsia/KRX");
            dataList.Add("Stocks\t014130\t한익스프레스\tAsia/KRX");
            dataList.Add("Stocks\t014160\t대영포장\tAsia/KRX");
            dataList.Add("Stocks\t014280\t금강공업\tAsia/KRX");
            dataList.Add("Stocks\t014285\t금강공업우\tAsia/KRX");
            dataList.Add("Stocks\t014350\t신일건업\tAsia/KRX");
            dataList.Add("Stocks\t014440\t영보화학\tAsia/KRX");
            dataList.Add("Stocks\t014530\t극동유화\tAsia/KRX");
            dataList.Add("Stocks\t014580\t백광소재\tAsia/KRX");
            dataList.Add("Stocks\t014680\t한솔케미칼\tAsia/KRX");
            dataList.Add("Stocks\t014710\t사조씨푸드\tAsia/KRX");
            dataList.Add("Stocks\t014790\t한라\tAsia/KRX");
            dataList.Add("Stocks\t014820\t동원시스템즈\tAsia/KRX");
            dataList.Add("Stocks\t014825\t동원시스템즈우\tAsia/KRX");
            dataList.Add("Stocks\t014830\t유니드\tAsia/KRX");
            dataList.Add("Stocks\t014910\t성문전자\tAsia/KRX");
            dataList.Add("Stocks\t014915\t성문전자우\tAsia/KRX");
            dataList.Add("Stocks\t014990\t인디에프\tAsia/KRX");
            dataList.Add("Stocks\t015020\t이스타코\tAsia/KRX");
            dataList.Add("Stocks\t015230\t대창단조\tAsia/KRX");
            dataList.Add("Stocks\t015260\t에이엔피\tAsia/KRX");
            dataList.Add("Stocks\t015350\t부산가스\tAsia/KRX");
            dataList.Add("Stocks\t015360\t예스코\tAsia/KRX");
            dataList.Add("Stocks\t015540\t핫텍\tAsia/KRX");
            dataList.Add("Stocks\t015590\t대경기계\tAsia/KRX");
            dataList.Add("Stocks\t015760\t한국전력\tAsia/KRX");
            dataList.Add("Stocks\t015860\t일진홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t015890\t태경산업\tAsia/KRX");
            dataList.Add("Stocks\t016090\t대현\tAsia/KRX");
            dataList.Add("Stocks\t016360\t삼성증권\tAsia/KRX");
            dataList.Add("Stocks\t016380\t동부제철\tAsia/KRX");
            dataList.Add("Stocks\t016385\t동부제철우\tAsia/KRX");
            dataList.Add("Stocks\t016450\t한세예스24홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t016580\t환인제약\tAsia/KRX");
            dataList.Add("Stocks\t016590\t신대양제지\tAsia/KRX");
            dataList.Add("Stocks\t016610\t동부증권\tAsia/KRX");
            dataList.Add("Stocks\t016710\t대성홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t016800\t퍼시스\tAsia/KRX");
            dataList.Add("Stocks\t016880\t웅진홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t017040\t광명전기\tAsia/KRX");
            dataList.Add("Stocks\t017180\t명문제약\tAsia/KRX");
            dataList.Add("Stocks\t017370\t우신시스템\tAsia/KRX");
            dataList.Add("Stocks\t017390\t서울가스\tAsia/KRX");
            dataList.Add("Stocks\t017550\t수산중공업\tAsia/KRX");
            dataList.Add("Stocks\t017670\tSK텔레콤\tAsia/KRX");
            dataList.Add("Stocks\t017800\t현대엘리베이\tAsia/KRX");
            dataList.Add("Stocks\t017810\t풀무원\tAsia/KRX");
            dataList.Add("Stocks\t017900\t광전자\tAsia/KRX");
            dataList.Add("Stocks\t017940\tE1\tAsia/KRX");
            dataList.Add("Stocks\t017960\t한국카본\tAsia/KRX");
            dataList.Add("Stocks\t018260\t삼성에스디에스\tAsia/KRX");
            dataList.Add("Stocks\t018470\t조일알미늄\tAsia/KRX");
            dataList.Add("Stocks\t018500\t동원금속\tAsia/KRX");
            dataList.Add("Stocks\t018670\tSK가스\tAsia/KRX");
            dataList.Add("Stocks\t018880\t한라비스테온공조\tAsia/KRX");
            dataList.Add("Stocks\t019170\t신풍제약\tAsia/KRX");
            dataList.Add("Stocks\t019175\t신풍제약우\tAsia/KRX");
            dataList.Add("Stocks\t019180\t티에이치엔\tAsia/KRX");
            dataList.Add("Stocks\t019300\t동일제지\tAsia/KRX");
            dataList.Add("Stocks\t019440\t세아특수강\tAsia/KRX");
            dataList.Add("Stocks\t019490\t하이트론\tAsia/KRX");
            dataList.Add("Stocks\t019680\t대교\tAsia/KRX");
            dataList.Add("Stocks\t019685\t대교우B\tAsia/KRX");
            dataList.Add("Stocks\t020000\t한섬\tAsia/KRX");
            dataList.Add("Stocks\t020120\t다우인큐브\tAsia/KRX");
            dataList.Add("Stocks\t020150\t일진머티리얼즈\tAsia/KRX");
            dataList.Add("Stocks\t020560\t아시아나항공\tAsia/KRX");
            dataList.Add("Stocks\t020760\t일진디스플\tAsia/KRX");
            dataList.Add("Stocks\t021050\t서원\tAsia/KRX");
            dataList.Add("Stocks\t021240\t코웨이\tAsia/KRX");
            dataList.Add("Stocks\t021820\t세원정공\tAsia/KRX");
            dataList.Add("Stocks\t021960\t케이비캐피탈\tAsia/KRX");
            dataList.Add("Stocks\t023000\t삼원강재\tAsia/KRX");
            dataList.Add("Stocks\t023150\tMH에탄올\tAsia/KRX");
            dataList.Add("Stocks\t023350\t한국종합기술\tAsia/KRX");
            dataList.Add("Stocks\t023450\t동남합성\tAsia/KRX");
            dataList.Add("Stocks\t023530\t롯데쇼핑\tAsia/KRX");
            dataList.Add("Stocks\t023590\t다우기술\tAsia/KRX");
            dataList.Add("Stocks\t023800\t인지컨트롤스\tAsia/KRX");
            dataList.Add("Stocks\t023810\t인팩\tAsia/KRX");
            dataList.Add("Stocks\t023960\t에쓰씨엔지니어링\tAsia/KRX");
            dataList.Add("Stocks\t024070\tWISCOM\tAsia/KRX");
            dataList.Add("Stocks\t024090\t디씨엠\tAsia/KRX");
            dataList.Add("Stocks\t024110\t기업은행\tAsia/KRX");
            dataList.Add("Stocks\t024720\t한국콜마홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t024890\t대원화성\tAsia/KRX");
            dataList.Add("Stocks\t024900\t덕양산업\tAsia/KRX");
            dataList.Add("Stocks\t025000\tKPX케미칼\tAsia/KRX");
            dataList.Add("Stocks\t025530\tSJM홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t025540\t한국단자\tAsia/KRX");
            dataList.Add("Stocks\t025560\t미래산업\tAsia/KRX");
            dataList.Add("Stocks\t025620\t신우\tAsia/KRX");
            dataList.Add("Stocks\t025750\t한솔홈데코\tAsia/KRX");
            dataList.Add("Stocks\t025820\t이구산업\tAsia/KRX");
            dataList.Add("Stocks\t025850\t한화화인케미칼\tAsia/KRX");
            dataList.Add("Stocks\t025860\t남해화학\tAsia/KRX");
            dataList.Add("Stocks\t025890\t한국주강\tAsia/KRX");
            dataList.Add("Stocks\t026890\t디피씨\tAsia/KRX");
            dataList.Add("Stocks\t026940\t부국철강\tAsia/KRX");
            dataList.Add("Stocks\t027390\t한화갤러리아타임월드\tAsia/KRX");
            dataList.Add("Stocks\t027410\tBGF리테일\tAsia/KRX");
            dataList.Add("Stocks\t027740\t마니커\tAsia/KRX");
            dataList.Add("Stocks\t027970\t세하\tAsia/KRX");
            dataList.Add("Stocks\t028050\t삼성엔지니어링\tAsia/KRX");
            dataList.Add("Stocks\t028100\t동아지질\tAsia/KRX");
            dataList.Add("Stocks\t028260\t제일모직\tAsia/KRX");
            dataList.Add("Stocks\t028670\t팬오션\tAsia/KRX");
            dataList.Add("Stocks\t029460\t케이씨텍\tAsia/KRX");
            dataList.Add("Stocks\t029530\t신도리코\tAsia/KRX");
            dataList.Add("Stocks\t029780\t삼성카드\tAsia/KRX");
            dataList.Add("Stocks\t030000\t제일기획\tAsia/KRX");
            dataList.Add("Stocks\t030200\tKT\tAsia/KRX");
            dataList.Add("Stocks\t030210\tKTB투자증권\tAsia/KRX");
            dataList.Add("Stocks\t030610\t교보증권\tAsia/KRX");
            dataList.Add("Stocks\t030720\t동원수산\tAsia/KRX");
            dataList.Add("Stocks\t030790\t동양네트웍스\tAsia/KRX");
            dataList.Add("Stocks\t031430\t신세계인터내셔날\tAsia/KRX");
            dataList.Add("Stocks\t031440\t신세계푸드\tAsia/KRX");
            dataList.Add("Stocks\t031820\t콤텍시스템\tAsia/KRX");
            dataList.Add("Stocks\t032350\t롯데관광개발\tAsia/KRX");
            dataList.Add("Stocks\t032560\t황금에스티\tAsia/KRX");
            dataList.Add("Stocks\t032640\tLG유플러스\tAsia/KRX");
            dataList.Add("Stocks\t032830\t삼성생명\tAsia/KRX");
            dataList.Add("Stocks\t033180\t필룩스\tAsia/KRX");
            dataList.Add("Stocks\t033240\t자화전자\tAsia/KRX");
            dataList.Add("Stocks\t033250\t체시스\tAsia/KRX");
            dataList.Add("Stocks\t033270\t유나이티드제약\tAsia/KRX");
            dataList.Add("Stocks\t033530\t세종공업\tAsia/KRX");
            dataList.Add("Stocks\t033660\t아주캐피탈\tAsia/KRX");
            dataList.Add("Stocks\t033780\tKT&G\tAsia/KRX");
            dataList.Add("Stocks\t033920\t무학\tAsia/KRX");
            dataList.Add("Stocks\t034020\t두산중공업\tAsia/KRX");
            dataList.Add("Stocks\t034120\tSBS\tAsia/KRX");
            dataList.Add("Stocks\t034220\tLG디스플레이\tAsia/KRX");
            dataList.Add("Stocks\t034300\t신세계건설\tAsia/KRX");
            dataList.Add("Stocks\t034310\tNICE\tAsia/KRX");
            dataList.Add("Stocks\t034590\t인천도시가스\tAsia/KRX");
            dataList.Add("Stocks\t034730\tSK C&C\tAsia/KRX");
            dataList.Add("Stocks\t035000\tGⅡR\tAsia/KRX");
            dataList.Add("Stocks\t035150\t백산\tAsia/KRX");
            dataList.Add("Stocks\t035250\t강원랜드\tAsia/KRX");
            dataList.Add("Stocks\t035420\tNAVER\tAsia/KRX");
            dataList.Add("Stocks\t035510\t신세계 I&C\tAsia/KRX");
            dataList.Add("Stocks\t036460\t한국가스공사\tAsia/KRX");
            dataList.Add("Stocks\t036530\tS&T홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t036570\t엔씨소프트\tAsia/KRX");
            dataList.Add("Stocks\t036580\t팜스코\tAsia/KRX");
            dataList.Add("Stocks\t037270\tYG PLUS\tAsia/KRX");
            dataList.Add("Stocks\t037560\tCJ헬로비전\tAsia/KRX");
            dataList.Add("Stocks\t037620\t미래에셋증권\tAsia/KRX");
            dataList.Add("Stocks\t037710\t광주신세계\tAsia/KRX");
            dataList.Add("Stocks\t039130\t하나투어\tAsia/KRX");
            dataList.Add("Stocks\t039490\t키움증권\tAsia/KRX");
            dataList.Add("Stocks\t041650\t상신브레이크\tAsia/KRX");
            dataList.Add("Stocks\t042660\t대우조선해양\tAsia/KRX");
            dataList.Add("Stocks\t042670\t두산인프라코어\tAsia/KRX");
            dataList.Add("Stocks\t042700\t한미반도체\tAsia/KRX");
            dataList.Add("Stocks\t044380\t주연테크\tAsia/KRX");
            dataList.Add("Stocks\t044450\tKSS해운\tAsia/KRX");
            dataList.Add("Stocks\t044820\t코스맥스비티아이\tAsia/KRX");
            dataList.Add("Stocks\t047040\t대우건설\tAsia/KRX");
            dataList.Add("Stocks\t047050\t대우인터내셔널\tAsia/KRX");
            dataList.Add("Stocks\t047400\t쌍용머티리얼\tAsia/KRX");
            dataList.Add("Stocks\t047810\t한국항공우주\tAsia/KRX");
            dataList.Add("Stocks\t049770\t동원F&B\tAsia/KRX");
            dataList.Add("Stocks\t049800\t우진플라임\tAsia/KRX");
            dataList.Add("Stocks\t051310\t포스코플랜텍\tAsia/KRX");
            dataList.Add("Stocks\t051600\t한전KPS\tAsia/KRX");
            dataList.Add("Stocks\t051630\t진양화학\tAsia/KRX");
            dataList.Add("Stocks\t051900\tLG생활건강\tAsia/KRX");
            dataList.Add("Stocks\t051905\tLG생활건강우\tAsia/KRX");
            dataList.Add("Stocks\t051910\tLG화학\tAsia/KRX");
            dataList.Add("Stocks\t051915\tLG화학우\tAsia/KRX");
            dataList.Add("Stocks\t052690\t한전기술\tAsia/KRX");
            dataList.Add("Stocks\t053210\t스카이라이프\tAsia/KRX");
            dataList.Add("Stocks\t053690\t한미글로벌\tAsia/KRX");
            dataList.Add("Stocks\t055550\t신한지주\tAsia/KRX");
            dataList.Add("Stocks\t057050\t현대홈쇼핑\tAsia/KRX");
            dataList.Add("Stocks\t058430\t포스코강판\tAsia/KRX");
            dataList.Add("Stocks\t058650\t세아홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t058730\t동아에스텍\tAsia/KRX");
            dataList.Add("Stocks\t058850\tKTcs\tAsia/KRX");
            dataList.Add("Stocks\t058860\t케이티스\tAsia/KRX");
            dataList.Add("Stocks\t060980\t한라홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t063160\t종근당바이오\tAsia/KRX");
            dataList.Add("Stocks\t064350\t현대로템\tAsia/KRX");
            dataList.Add("Stocks\t064960\tS&T모티브\tAsia/KRX");
            dataList.Add("Stocks\t066570\tLG전자\tAsia/KRX");
            dataList.Add("Stocks\t066575\tLG전자우\tAsia/KRX");
            dataList.Add("Stocks\t067830\t세이브존I&C\tAsia/KRX");
            dataList.Add("Stocks\t068290\t삼성출판사\tAsia/KRX");
            dataList.Add("Stocks\t068400\tAJ렌터카\tAsia/KRX");
            dataList.Add("Stocks\t068870\tLG생명과학\tAsia/KRX");
            dataList.Add("Stocks\t068875\tLG생명과학우\tAsia/KRX");
            dataList.Add("Stocks\t069260\t휴켐스\tAsia/KRX");
            dataList.Add("Stocks\t069460\t대호에이엘\tAsia/KRX");
            dataList.Add("Stocks\t069500\tKODEX 200\tAsia/KRX");
            dataList.Add("Stocks\t069620\t대웅제약\tAsia/KRX");
            dataList.Add("Stocks\t069640\t엠케이트렌드\tAsia/KRX");
            dataList.Add("Stocks\t069660\tKOSEF 200\tAsia/KRX");
            dataList.Add("Stocks\t069730\tDSR제강\tAsia/KRX");
            dataList.Add("Stocks\t069960\t현대백화점\tAsia/KRX");
            dataList.Add("Stocks\t071050\t한국금융지주\tAsia/KRX");
            dataList.Add("Stocks\t071055\t한국금융지주우\tAsia/KRX");
            dataList.Add("Stocks\t071090\t하이스틸\tAsia/KRX");
            dataList.Add("Stocks\t071320\t지역난방공사\tAsia/KRX");
            dataList.Add("Stocks\t071840\t롯데하이마트\tAsia/KRX");
            dataList.Add("Stocks\t071950\t코아스\tAsia/KRX");
            dataList.Add("Stocks\t071970\tSTX중공업\tAsia/KRX");
            dataList.Add("Stocks\t072130\t유엔젤\tAsia/KRX");
            dataList.Add("Stocks\t072710\t농심홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t073240\t금호타이어\tAsia/KRX");
            dataList.Add("Stocks\t074610\t이엔쓰리\tAsia/KRX");
            dataList.Add("Stocks\t075180\t새론오토모티브\tAsia/KRX");
            dataList.Add("Stocks\t077500\t유니퀘스트\tAsia/KRX");
            dataList.Add("Stocks\t077970\tSTX엔진\tAsia/KRX");
            dataList.Add("Stocks\t078000\t텔코웨어\tAsia/KRX");
            dataList.Add("Stocks\t078520\t에이블씨엔씨\tAsia/KRX");
            dataList.Add("Stocks\t078930\tGS\tAsia/KRX");
            dataList.Add("Stocks\t078935\tGS우\tAsia/KRX");
            dataList.Add("Stocks\t079160\tCJ CGV\tAsia/KRX");
            dataList.Add("Stocks\t079430\t현대리바트\tAsia/KRX");
            dataList.Add("Stocks\t079660\t사조해표\tAsia/KRX");
            dataList.Add("Stocks\t079980\t휴비스\tAsia/KRX");
            dataList.Add("Stocks\t081000\t일진다이아\tAsia/KRX");
            dataList.Add("Stocks\t081660\t휠라코리아\tAsia/KRX");
            dataList.Add("Stocks\t081930\t아시아8호\tAsia/KRX");
            dataList.Add("Stocks\t082240\t아시아5호\tAsia/KRX");
            dataList.Add("Stocks\t082250\t아시아6호\tAsia/KRX");
            dataList.Add("Stocks\t082260\t아시아7호\tAsia/KRX");
            dataList.Add("Stocks\t082640\t동양생명\tAsia/KRX");
            dataList.Add("Stocks\t082740\t두산엔진\tAsia/KRX");
            dataList.Add("Stocks\t083350\t동북아10호\tAsia/KRX");
            dataList.Add("Stocks\t083360\t동북아11호\tAsia/KRX");
            dataList.Add("Stocks\t083370\t동북아12호\tAsia/KRX");
            dataList.Add("Stocks\t083380\t동북아13호\tAsia/KRX");
            dataList.Add("Stocks\t083390\t동북아14호\tAsia/KRX");
            dataList.Add("Stocks\t083420\tKPX그린케미칼\tAsia/KRX");
            dataList.Add("Stocks\t083570\t아시아10호\tAsia/KRX");
            dataList.Add("Stocks\t083580\t아시아11호\tAsia/KRX");
            dataList.Add("Stocks\t083590\t아시아12호\tAsia/KRX");
            dataList.Add("Stocks\t083600\t아시아13호\tAsia/KRX");
            dataList.Add("Stocks\t083610\t아시아14호\tAsia/KRX");
            dataList.Add("Stocks\t083620\t아시아15호\tAsia/KRX");
            dataList.Add("Stocks\t084010\t대한제강\tAsia/KRX");
            dataList.Add("Stocks\t084670\t동양고속\tAsia/KRX");
            dataList.Add("Stocks\t084680\t이월드\tAsia/KRX");
            dataList.Add("Stocks\t084690\t대상홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t084695\t대상홀딩스우\tAsia/KRX");
            dataList.Add("Stocks\t084870\t베이직하우스\tAsia/KRX");
            dataList.Add("Stocks\t085310\t엔케이\tAsia/KRX");
            dataList.Add("Stocks\t086280\t현대글로비스\tAsia/KRX");
            dataList.Add("Stocks\t086790\t하나금융지주\tAsia/KRX");
            dataList.Add("Stocks\t088350\t한화생명\tAsia/KRX");
            dataList.Add("Stocks\t088790\t진도\tAsia/KRX");
            dataList.Add("Stocks\t088980\t맥쿼리인프라\tAsia/KRX");
            dataList.Add("Stocks\t089470\t현대EP\tAsia/KRX");
            dataList.Add("Stocks\t090080\t평화산업\tAsia/KRX");
            dataList.Add("Stocks\t090350\t노루페인트\tAsia/KRX");
            dataList.Add("Stocks\t090355\t노루페인트우\tAsia/KRX");
            dataList.Add("Stocks\t090370\t아비스타\tAsia/KRX");
            dataList.Add("Stocks\t090430\t아모레퍼시픽\tAsia/KRX");
            dataList.Add("Stocks\t090435\t아모레퍼시픽우\tAsia/KRX");
            dataList.Add("Stocks\t090970\t코리아01호\tAsia/KRX");
            dataList.Add("Stocks\t090980\t코리아02호\tAsia/KRX");
            dataList.Add("Stocks\t090990\t코리아03호\tAsia/KRX");
            dataList.Add("Stocks\t091000\t코리아04호\tAsia/KRX");
            dataList.Add("Stocks\t091090\t세원셀론텍\tAsia/KRX");
            dataList.Add("Stocks\t091160\tKODEX 반도체\tAsia/KRX");
            dataList.Add("Stocks\t091170\tKODEX 은행\tAsia/KRX");
            dataList.Add("Stocks\t091180\tKODEX 자동차\tAsia/KRX");
            dataList.Add("Stocks\t091200\tKOSEF IT\tAsia/KRX");
            dataList.Add("Stocks\t091210\tTIGER KRX100\tAsia/KRX");
            dataList.Add("Stocks\t091220\tTIGER 은행\tAsia/KRX");
            dataList.Add("Stocks\t091230\tTIGER 반도체\tAsia/KRX");
            dataList.Add("Stocks\t092200\t디아이씨\tAsia/KRX");
            dataList.Add("Stocks\t092220\tKEC\tAsia/KRX");
            dataList.Add("Stocks\t092230\tKPX홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t092440\t기신정기\tAsia/KRX");
            dataList.Add("Stocks\t092630\t바다로3호\tAsia/KRX");
            dataList.Add("Stocks\t093050\tLF\tAsia/KRX");
            dataList.Add("Stocks\t093230\t이필름\tAsia/KRX");
            dataList.Add("Stocks\t093240\t에리트베이직\tAsia/KRX");
            dataList.Add("Stocks\t093370\t후성\tAsia/KRX");
            dataList.Add("Stocks\t094280\t효성ITX\tAsia/KRX");
            dataList.Add("Stocks\t094800\t맵스리얼티1\tAsia/KRX");
            dataList.Add("Stocks\t095720\t웅진씽크빅\tAsia/KRX");
            dataList.Add("Stocks\t096300\t베트남개발1\tAsia/KRX");
            dataList.Add("Stocks\t096760\tJW홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t096770\tSK이노베이션\tAsia/KRX");
            dataList.Add("Stocks\t096775\tSK이노베이션우\tAsia/KRX");
            dataList.Add("Stocks\t097230\t한진중공업\tAsia/KRX");
            dataList.Add("Stocks\t097710\tTIGER 가치주\tAsia/KRX");
            dataList.Add("Stocks\t097720\tTIGER 미드캡\tAsia/KRX");
            dataList.Add("Stocks\t097750\tTREX 중소형가치\tAsia/KRX");
            dataList.Add("Stocks\t097950\tCJ제일제당\tAsia/KRX");
            dataList.Add("Stocks\t097955\tCJ제일제당 우\tAsia/KRX");
            dataList.Add("Stocks\t098560\tTIGER 미디어통신\tAsia/KRX");
            dataList.Add("Stocks\t099140\tKODEX China H\tAsia/KRX");
            dataList.Add("Stocks\t099340\t하나니켈1호\tAsia/KRX");
            dataList.Add("Stocks\t099350\t하나니켈2호\tAsia/KRX");
            dataList.Add("Stocks\t100220\t비상교육\tAsia/KRX");
            dataList.Add("Stocks\t100250\t진양홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t100840\tS&TC\tAsia/KRX");
            dataList.Add("Stocks\t100910\tKOSEF KRX100\tAsia/KRX");
            dataList.Add("Stocks\t101060\tSBS미디어홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t101140\t아티스\tAsia/KRX");
            dataList.Add("Stocks\t101280\tKODEX Japan\tAsia/KRX");
            dataList.Add("Stocks\t102110\tTIGER 200\tAsia/KRX");
            dataList.Add("Stocks\t102260\t동성홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t102280\t쌍방울\tAsia/KRX");
            dataList.Add("Stocks\t102460\t이연제약\tAsia/KRX");
            dataList.Add("Stocks\t102780\tKODEX 삼성그룹\tAsia/KRX");
            dataList.Add("Stocks\t102960\tKODEX 조선\tAsia/KRX");
            dataList.Add("Stocks\t102970\tKODEX 증권\tAsia/KRX");
            dataList.Add("Stocks\t103130\t웅진에너지\tAsia/KRX");
            dataList.Add("Stocks\t103140\t풍산\tAsia/KRX");
            dataList.Add("Stocks\t103590\t일진전기\tAsia/KRX");
            dataList.Add("Stocks\t104110\t신성이엔지\tAsia/KRX");
            dataList.Add("Stocks\t104120\t신성에프에이\tAsia/KRX");
            dataList.Add("Stocks\t104520\tKOSEF 블루칩\tAsia/KRX");
            dataList.Add("Stocks\t104530\tKOSEF 고배당\tAsia/KRX");
            dataList.Add("Stocks\t104580\tKODEX Brazil\tAsia/KRX");
            dataList.Add("Stocks\t104700\t한국철강\tAsia/KRX");
            dataList.Add("Stocks\t105010\tTIGER 라틴\tAsia/KRX");
            dataList.Add("Stocks\t105020\tTIGER 브릭스\tAsia/KRX");
            dataList.Add("Stocks\t105190\tKINDEX200\tAsia/KRX");
            dataList.Add("Stocks\t105270\tKINDEX 성장대형F15\tAsia/KRX");
            dataList.Add("Stocks\t105560\tKB금융\tAsia/KRX");
            dataList.Add("Stocks\t105630\t한세실업\tAsia/KRX");
            dataList.Add("Stocks\t105780\tKStar 5대그룹주\tAsia/KRX");
            dataList.Add("Stocks\t105840\t우진\tAsia/KRX");
            dataList.Add("Stocks\t107560\tGIANT 현대차그룹\tAsia/KRX");
            dataList.Add("Stocks\t107590\t미원에스씨\tAsia/KRX");
            dataList.Add("Stocks\t108440\tKINDEX 코스닥스타\tAsia/KRX");
            dataList.Add("Stocks\t108450\tKINDEX 삼성그룹SW\tAsia/KRX");
            dataList.Add("Stocks\t108480\tKStar 코스닥엘리트30\tAsia/KRX");
            dataList.Add("Stocks\t108590\tTREX 200\tAsia/KRX");
            dataList.Add("Stocks\t108630\tFIRST 스타우량\tAsia/KRX");
            dataList.Add("Stocks\t108670\tLG하우시스\tAsia/KRX");
            dataList.Add("Stocks\t108675\tLG하우시스우\tAsia/KRX");
            dataList.Add("Stocks\t109070\tKGP\tAsia/KRX");
            dataList.Add("Stocks\t110570\t넥솔론\tAsia/KRX");
            dataList.Add("Stocks\t111770\t영원무역\tAsia/KRX");
            dataList.Add("Stocks\t112610\t씨에스윈드\tAsia/KRX");
            dataList.Add("Stocks\t114090\tGKL\tAsia/KRX");
            dataList.Add("Stocks\t114100\tKStar 국고채\tAsia/KRX");
            dataList.Add("Stocks\t114260\tKODEX 국고채\tAsia/KRX");
            dataList.Add("Stocks\t114460\tKINDEX 국고채\tAsia/KRX");
            dataList.Add("Stocks\t114470\tKOSEF 국고채\tAsia/KRX");
            dataList.Add("Stocks\t114800\tKODEX 인버스\tAsia/KRX");
            dataList.Add("Stocks\t114820\tTIGER 국채3\tAsia/KRX");
            dataList.Add("Stocks\t115390\t락앤락\tAsia/KRX");
            dataList.Add("Stocks\t117460\tKODEX 에너지화학\tAsia/KRX");
            dataList.Add("Stocks\t117580\t대성에너지\tAsia/KRX");
            dataList.Add("Stocks\t117680\tKODEX 철강\tAsia/KRX");
            dataList.Add("Stocks\t117690\tTIGER 차이나\tAsia/KRX");
            dataList.Add("Stocks\t117700\tKODEX 건설\tAsia/KRX");
            dataList.Add("Stocks\t117740\tARIRANG LG그룹&\tAsia/KRX");
            dataList.Add("Stocks\t117930\t한진해운\tAsia/KRX");
            dataList.Add("Stocks\t118000\t우리들휴브레인\tAsia/KRX");
            dataList.Add("Stocks\t119650\tKC코트렐\tAsia/KRX");
            dataList.Add("Stocks\t120030\t조선선재\tAsia/KRX");
            dataList.Add("Stocks\t120110\t코오롱인더\tAsia/KRX");
            dataList.Add("Stocks\t120115\t코오롱인더우\tAsia/KRX");
            dataList.Add("Stocks\t120210\tGREAT SRI\tAsia/KRX");
            dataList.Add("Stocks\t121550\t코크렙15호\tAsia/KRX");
            dataList.Add("Stocks\t122090\tARIRANG KOSPI50\tAsia/KRX");
            dataList.Add("Stocks\t122260\tKOSEF 통안채\tAsia/KRX");
            dataList.Add("Stocks\t122390\tTIGER 코스닥프리미어\tAsia/KRX");
            dataList.Add("Stocks\t122630\tKODEX 레버리지\tAsia/KRX");
            dataList.Add("Stocks\t122900\t아이마켓코리아\tAsia/KRX");
            dataList.Add("Stocks\t123310\tTIGER 인버스\tAsia/KRX");
            dataList.Add("Stocks\t123320\tTIGER 레버리지\tAsia/KRX");
            dataList.Add("Stocks\t123690\t한국화장품\tAsia/KRX");
            dataList.Add("Stocks\t123700\tSJM\tAsia/KRX");
            dataList.Add("Stocks\t123760\tKStar 레버리지\tAsia/KRX");
            dataList.Add("Stocks\t126560\t현대에이치씨엔\tAsia/KRX");
            dataList.Add("Stocks\t128820\t대성산업\tAsia/KRX");
            dataList.Add("Stocks\t128940\t한미약품\tAsia/KRX");
            dataList.Add("Stocks\t129260\t인터지스\tAsia/KRX");
            dataList.Add("Stocks\t129270\tARIRANG 네오밸류\tAsia/KRX");
            dataList.Add("Stocks\t130660\t한전산업\tAsia/KRX");
            dataList.Add("Stocks\t130680\tTIGER 원유선물(H)\tAsia/KRX");
            dataList.Add("Stocks\t130730\tKOSEF 단기자금\tAsia/KRX");
            dataList.Add("Stocks\t131890\tKINDEX 삼성그룹EW\tAsia/KRX");
            dataList.Add("Stocks\t132030\tKODEX 골드선물(H)\tAsia/KRX");
            dataList.Add("Stocks\t133690\tTIGER 나스닥100\tAsia/KRX");
            dataList.Add("Stocks\t133820\t화인베스틸\tAsia/KRX");
            dataList.Add("Stocks\t134380\t미원화학\tAsia/KRX");
            dataList.Add("Stocks\t134790\t팀스\tAsia/KRX");
            dataList.Add("Stocks\t136280\tKODEX 소비재\tAsia/KRX");
            dataList.Add("Stocks\t136340\tKStar 우량회사채\tAsia/KRX");
            dataList.Add("Stocks\t136490\t선진\tAsia/KRX");
            dataList.Add("Stocks\t137610\tTIGER 농산물선물(H)\tAsia/KRX");
            dataList.Add("Stocks\t137930\t마이다스 커버드콜\tAsia/KRX");
            dataList.Add("Stocks\t137990\tTIGER 그린\tAsia/KRX");
            dataList.Add("Stocks\t138040\t메리츠금융지주\tAsia/KRX");
            dataList.Add("Stocks\t138210\tGREAT GREEN\tAsia/KRX");
            dataList.Add("Stocks\t138230\tKOSEF 달러선물\tAsia/KRX");
            dataList.Add("Stocks\t138440\t이코리아리츠\tAsia/KRX");
            dataList.Add("Stocks\t138490\t코오롱플라스틱\tAsia/KRX");
            dataList.Add("Stocks\t138520\tTIGER 삼성그룹\tAsia/KRX");
            dataList.Add("Stocks\t138530\tTIGER LG그룹+\tAsia/KRX");
            dataList.Add("Stocks\t138540\tTIGER 현대차그룹+\tAsia/KRX");
            dataList.Add("Stocks\t138910\tKODEX 구리선물(H)\tAsia/KRX");
            dataList.Add("Stocks\t138920\tKODEX 콩선물(H)\tAsia/KRX");
            dataList.Add("Stocks\t138930\tBS금융지주\tAsia/KRX");
            dataList.Add("Stocks\t139130\tDGB금융지주\tAsia/KRX");
            dataList.Add("Stocks\t139200\t하이골드2호\tAsia/KRX");
            dataList.Add("Stocks\t139220\tTIGER 건설기계\tAsia/KRX");
            dataList.Add("Stocks\t139230\tTIGER 조선운송\tAsia/KRX");
            dataList.Add("Stocks\t139240\tTIGER 철강소재\tAsia/KRX");
            dataList.Add("Stocks\t139250\tTIGER 에너지화학\tAsia/KRX");
            dataList.Add("Stocks\t139260\tTIGER IT\tAsia/KRX");
            dataList.Add("Stocks\t139270\tTIGER 금융\tAsia/KRX");
            dataList.Add("Stocks\t139280\tTIGER 경기방어\tAsia/KRX");
            dataList.Add("Stocks\t139290\tTIGER 경기소비재\tAsia/KRX");
            dataList.Add("Stocks\t139310\tTIGER 금속선물(H)\tAsia/KRX");
            dataList.Add("Stocks\t139320\tTIGER 금은선물(H)\tAsia/KRX");
            dataList.Add("Stocks\t139480\t이마트\tAsia/KRX");
            dataList.Add("Stocks\t139660\tKOSEF 달러인버스선물\tAsia/KRX");
            dataList.Add("Stocks\t140570\tKStar 수출주\tAsia/KRX");
            dataList.Add("Stocks\t140580\tKStar 우량업종\tAsia/KRX");
            dataList.Add("Stocks\t140700\tKODEX 보험\tAsia/KRX");
            dataList.Add("Stocks\t140710\tKODEX 운송\tAsia/KRX");
            dataList.Add("Stocks\t140890\t트러스제7호\tAsia/KRX");
            dataList.Add("Stocks\t140910\t광희리츠\tAsia/KRX");
            dataList.Add("Stocks\t140950\t파워 K100\tAsia/KRX");
            dataList.Add("Stocks\t141240\tARIRANG K100EW\tAsia/KRX");
            dataList.Add("Stocks\t141250\tARIRANG KRX100EW\tAsia/KRX");
            dataList.Add("Stocks\t143460\tKINDEX 밸류대형\tAsia/KRX");
            dataList.Add("Stocks\t143850\tTIGER S&P500선물(H)\tAsia/KRX");
            dataList.Add("Stocks\t143860\tTIGER 헬스케어\tAsia/KRX");
            dataList.Add("Stocks\t144600\tKODEX 은선물(H)\tAsia/KRX");
            dataList.Add("Stocks\t144620\t코오롱머티리얼\tAsia/KRX");
            dataList.Add("Stocks\t144670\tKOSEF 펀더멘탈대형주\tAsia/KRX");
            dataList.Add("Stocks\t145270\t케이탑리츠\tAsia/KRX");
            dataList.Add("Stocks\t145670\tKINDEX 인버스\tAsia/KRX");
            dataList.Add("Stocks\t145850\tTREX 펀더멘탈 200\tAsia/KRX");
            dataList.Add("Stocks\t145990\t삼양사\tAsia/KRX");
            dataList.Add("Stocks\t145995\t삼양사우\tAsia/KRX");
            dataList.Add("Stocks\t147970\tTIGER 모멘텀\tAsia/KRX");
            dataList.Add("Stocks\t148020\tKStar 200\tAsia/KRX");
            dataList.Add("Stocks\t148040\tPIONEER SRI\tAsia/KRX");
            dataList.Add("Stocks\t148070\tKOSEF 10년국고채\tAsia/KRX");
            dataList.Add("Stocks\t149130\t케이비부국위탁리츠\tAsia/KRX");
            dataList.Add("Stocks\t150460\tTIGER 중국소비테마\tAsia/KRX");
            dataList.Add("Stocks\t152100\tARIRANG 200\tAsia/KRX");
            dataList.Add("Stocks\t152180\tTIGER 생활소비재\tAsia/KRX");
            dataList.Add("Stocks\t152280\tKOSEF 200 선물\tAsia/KRX");
            dataList.Add("Stocks\t152380\tKODEX 10년국채선물\tAsia/KRX");
            dataList.Add("Stocks\t152500\tKINDEX 레버리지\tAsia/KRX");
            dataList.Add("Stocks\t152550\t한국ANKOR유전\tAsia/KRX");
            dataList.Add("Stocks\t152870\t파워 K200\tAsia/KRX");
            dataList.Add("Stocks\t153130\tKODEX 단기채권\tAsia/KRX");
            dataList.Add("Stocks\t153270\tiKon 100\tAsia/KRX");
            dataList.Add("Stocks\t153360\t하이골드3호\tAsia/KRX");
            dataList.Add("Stocks\t155660\tDSR\tAsia/KRX");
            dataList.Add("Stocks\t155900\t바다로19호\tAsia/KRX");
            dataList.Add("Stocks\t156080\tKODEX MSCI KOREA\tAsia/KRX");
            dataList.Add("Stocks\t157450\tTIGER 유동자금\tAsia/KRX");
            dataList.Add("Stocks\t157490\tTIGER 소프트웨어\tAsia/KRX");
            dataList.Add("Stocks\t157500\tTIGER 증권\tAsia/KRX");
            dataList.Add("Stocks\t157510\tTIGER 자동차\tAsia/KRX");
            dataList.Add("Stocks\t157520\tTIGER 화학\tAsia/KRX");
            dataList.Add("Stocks\t157650\tKStar 5대그룹주장기?\tAsia/KRX");
            dataList.Add("Stocks\t159650\t하이골드8호\tAsia/KRX");
            dataList.Add("Stocks\t159800\t마이티 K100\tAsia/KRX");
            dataList.Add("Stocks\t160580\tTIGER 구리실물\tAsia/KRX");
            dataList.Add("Stocks\t161000\t애경유화\tAsia/KRX");
            dataList.Add("Stocks\t161390\t한국타이어\tAsia/KRX");
            dataList.Add("Stocks\t161490\tARIRANG 방어주\tAsia/KRX");
            dataList.Add("Stocks\t161500\tARIRANG 주도주\tAsia/KRX");
            dataList.Add("Stocks\t161510\tARIRANG 고배당주\tAsia/KRX");
            dataList.Add("Stocks\t161520\tARIRANG 자동차\tAsia/KRX");
            dataList.Add("Stocks\t161530\tARIRANG 조선운송\tAsia/KRX");
            dataList.Add("Stocks\t161540\tARIRANG 철강금속\tAsia/KRX");
            dataList.Add("Stocks\t161550\tARIRANG 화학\tAsia/KRX");
            dataList.Add("Stocks\t161890\t한국콜마\tAsia/KRX");
            dataList.Add("Stocks\t163560\t동일고무벨트\tAsia/KRX");
            dataList.Add("Stocks\t166060\tKODEX 주식&골드(H)\tAsia/KRX");
            dataList.Add("Stocks\t166400\tTIGER 커버드C200\tAsia/KRX");
            dataList.Add("Stocks\t167860\tKOSEF 10년국고채 레?\tAsia/KRX");
            dataList.Add("Stocks\t168300\tKTOP50\tAsia/KRX");
            dataList.Add("Stocks\t168490\t한국패러랠\tAsia/KRX");
            dataList.Add("Stocks\t168580\tKINDEX 중국본토CSI30\tAsia/KRX");
            dataList.Add("Stocks\t169950\tKODEX CHINA A50\tAsia/KRX");
            dataList.Add("Stocks\t170350\tTIGER 베타플러스\tAsia/KRX");
            dataList.Add("Stocks\t170900\t동아에스티\tAsia/KRX");
            dataList.Add("Stocks\t172580\t하이골드12호\tAsia/KRX");
            dataList.Add("Stocks\t174350\tTIGER 로우볼\tAsia/KRX");
            dataList.Add("Stocks\t174360\tKStar 중국본토 CSI10\tAsia/KRX");
            dataList.Add("Stocks\t175330\tJB금융지주\tAsia/KRX");
            dataList.Add("Stocks\t176710\t파워 국고채 ETF\tAsia/KRX");
            dataList.Add("Stocks\t176950\tKODEX 인버스국채선물\tAsia/KRX");
            dataList.Add("Stocks\t180640\t한진칼\tAsia/KRX");
            dataList.Add("Stocks\t181450\tKINDEX 합성-선진국하\tAsia/KRX");
            dataList.Add("Stocks\t181480\tKINDEX 합성-미국리츠\tAsia/KRX");
            dataList.Add("Stocks\t181710\tNHN엔터테인먼트\tAsia/KRX");
            dataList.Add("Stocks\t182480\tTIGER합성-MSCI US리?\tAsia/KRX");
            dataList.Add("Stocks\t182490\tTIGER 합성-단기선진?\tAsia/KRX");
            dataList.Add("Stocks\t183190\t아세아시멘트\tAsia/KRX");
            dataList.Add("Stocks\t183700\tKStar 채권혼합\tAsia/KRX");
            dataList.Add("Stocks\t183710\tKStar 주식혼합\tAsia/KRX");
            dataList.Add("Stocks\t185680\tKODEX 합성-미국바이?\tAsia/KRX");
            dataList.Add("Stocks\t185750\t종근당\tAsia/KRX");
            dataList.Add("Stocks\t189400\tARIRANG 합성-AC 월드\tAsia/KRX");
            dataList.Add("Stocks\t190150\tARIRANG 바벨 채권\tAsia/KRX");
            dataList.Add("Stocks\t190160\tARIRANG 단기유동성\tAsia/KRX");
            dataList.Add("Stocks\t190620\tKINDEX 단기자금\tAsia/KRX");
            dataList.Add("Stocks\t192090\tTIGER 차이나A300\tAsia/KRX");
            dataList.Add("Stocks\t192400\t쿠쿠전자\tAsia/KRX");
            dataList.Add("Stocks\t192520\t경남은행\tAsia/KRX");
            dataList.Add("Stocks\t192530\t광주은행\tAsia/KRX");
            dataList.Add("Stocks\t192720\t파워고배당저변동성\tAsia/KRX");
            dataList.Add("Stocks\t192820\t코스맥스\tAsia/KRX");
            dataList.Add("Stocks\t195920\tTIGER 합성-일본(H)\tAsia/KRX");
            dataList.Add("Stocks\t195930\tTIGER 합성-유로스탁?\tAsia/KRX");
            dataList.Add("Stocks\t195970\tARIRANG 합성-선진국(\tAsia/KRX");
            dataList.Add("Stocks\t195980\tARIRANG 합성-신흥국(\tAsia/KRX");
            dataList.Add("Stocks\t196030\tKINDEX 일본레버리지(\tAsia/KRX");
            dataList.Add("Stocks\t196220\tKStar 일본레버리지(H\tAsia/KRX");
            dataList.Add("Stocks\t196230\tKStar 단기통안채\tAsia/KRX");
            dataList.Add("Stocks\t200020\tKODEX 합성-미국IT\tAsia/KRX");
            dataList.Add("Stocks\t200030\tKODEX 합성-미국산업?\tAsia/KRX");
            dataList.Add("Stocks\t200040\tKODEX 합성-미국금융\tAsia/KRX");
            dataList.Add("Stocks\t200050\tKODEX 합성-MSCI독일\tAsia/KRX");
            dataList.Add("Stocks\t200250\tKOSEF 합성-인디아(H)\tAsia/KRX");
            dataList.Add("Stocks\t200880\t한일이화\tAsia/KRX");
            dataList.Add("Stocks\t203780\tTIGER 나스닥바이오\tAsia/KRX");
            dataList.Add("Stocks\t204320\t만도\tAsia/KRX");
            dataList.Add("Stocks\t204420\tARIRANG 합성-차이나H\tAsia/KRX");
            dataList.Add("Stocks\t204450\tKODEX China H 레버리\tAsia/KRX");
            dataList.Add("Stocks\t204480\tTIGER 합성-차이나A레\tAsia/KRX");
            dataList.Add("Stocks\t205720\tKINDEX 합성-일본인버\tAsia/KRX");
            dataList.Add("Stocks\t208470\tSMART 합성-MSCI 선진\tAsia/KRX");
            dataList.Add("Stocks\t210540\t디와이파워\tAsia/KRX");
            dataList.Add("Stocks\t210780\tTIGER 코스피고배당\tAsia/KRX");
            dataList.Add("Stocks\t211210\t마이티 코스피고배당\tAsia/KRX");
            dataList.Add("Stocks\t211260\tKINDEX 배당성장\tAsia/KRX");
            dataList.Add("Stocks\t211560\tTIGER 배당성장\tAsia/KRX");
            dataList.Add("Stocks\t211900\tKODEX 배당성장\tAsia/KRX");
            dataList.Add("Stocks\t213500\t한솔제지\tAsia/KRX");
            dataList.Add("Stocks\t213610\tKODEX 삼성그룹밸류\tAsia/KRX");
            dataList.Add("Stocks\t213630\tARIRANG 합성-미국 고\tAsia/KRX");
            dataList.Add("Stocks\t500001\t신한 K200 USD 선물 ?\tAsia/KRX");
            dataList.Add("Stocks\t500002\t신한 USD K200 선물 ?\tAsia/KRX");
            dataList.Add("Stocks\t520001\t대우 로우볼 ETN\tAsia/KRX");
            dataList.Add("Stocks\t530001\tPerfex 유럽 고배당 ?\tAsia/KRX");
            dataList.Add("Stocks\t550001\tocto Big Vol ETN\tAsia/KRX");
            dataList.Add("Stocks\t550002\tocto WISE 배당 ETN\tAsia/KRX");
            dataList.Add("Stocks\t570001\tTRUE 코스피 선물매수\tAsia/KRX");
            dataList.Add("Stocks\t570002\tTRUE 코스피 선물매도\tAsia/KRX");
            dataList.Add("Stocks\t580001\table 코스피200선물플\tAsia/KRX");
            dataList.Add("Stocks\t580002\table Quant비중조절 E\tAsia/KRX");
            dataList.Add("Stocks\t900050\t중국원양자원\tAsia/KRX");
            dataList.Add("Stocks\t900140\t코라오홀딩스\tAsia/KRX");
            dataList.Add("Stocks\t950010\t평산차업 KDR\tAsia/KRX");

            return dataList;
        }
    }
}
